### PR TITLE
Added streamable __ids endpoint

### PR DESCRIPTION
**Pull request by catalin-ilea**

### CODE REVIEW

**Comment by ghost** [comment]
mostly lgtm.
the combination of a select block and WaitGroup is slightly scary! (probably predates this pr though)
Not sure if the concurrency there can be made simpler.

**Comment by catalin-ilea** [comment]
Can I merge this for now and look into simplifying concurrency separately?

**Comment by tosan88** [comment]
:+1:

**Comment by ghost** [comment]
sure.

**Pull request merged**
